version: '3'
services:
  chatty_test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    depends_on:
    - postgres_test
    volumes:
    - .:/user/src/app
    environment:
      DATABASE_URL: postgres://chattyapp_test@postgres/chatty
  postgres_test:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: chattyapp_test
      POSTGERES_DB: chatty
