version: '3'
services:
  chatty_test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      postgres_test:
        condition:service_healthy
    environment:
      DATABASE_URL: postgresql://chattyapp_test@postgres_test/chatty
  postgres_test:
    image: postgres:9.6.2-alpine
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: chattyapp_test
      POSTGERES_DB: chatty
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
