version: '3'
services:
  chatty:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - postgres
    environment:
      DATABASE_URL: postgresql://chattyapp@postgres/chatty
  postgres:
    image: postgres:9.6.2-alpine
    volumes:
    - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: chattyapp
      POSTGRES_DB: chatty 
